dist: trusty
sudo: required
language: node_js
cache:
  directories:
    - ~/.npm
install:
  - npm install

script:
  - cd modules/video && npm install && cd ../../
  - cd dride-ws && npm install && cd ../
  - sudo mkdir /dride
  - sudo mkdir /dride/thumb
  - sudo mkdir /dride/clip
  - sudo npm run test
notifications:
  email:
    - yossi@dride.io
node_js:
  - '8'

after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
