language: python

before_install:
 - sudo apt-get update

install:
 - sudo apt-get install python-dev python-numpy

before_script:
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make -j4 install
  - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages

python:
  - "2.7"

script:
  # We don't have Matlab on the Travis machines, so we're setting a dummy path
  # and ignoring the tests tagged for Matlab.
  - export MATLAB_LIBRARY_ROOT=/tmp
  - sbt "testOnly * -- -l MatlabTest"

  - python /home/travis/build/CardiganCam/Cardigan/cardiganTest.py

notifications:
  email:
    - saoron@gmail.com