language: python

compiler:
  - gcc

before_install:
 - sudo apt-get update

install:
 - sudo apt-get install python-dev python-numpy 
 - sudo apt-get install build-essential
 - sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
 - sudo apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
 - sudo apt-get install -y build-essential
 - sudo apt-get install libjpeg8-dev libtiff4-dev libjasper-dev libpng12-dev
 
before_script:
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local  -DWITH_IPP=OFF ..
  - make -j4
  - sudo make -j4 install
  - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages:/home/travis/build/CardiganCam/Cardigan

python:
  - "2.7"

script:

  - python /home/travis/build/CardiganCam/Cardigan/test/test_lane_detection.py

notifications:
  email:
    - erim32000@gmail.com
